version: "3"
services:
  jobmanager:
    image: thebozzcl/flink:arm32v7-1.11-scala_2.12-8-jre
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.role==manager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 4
        taskmanager.memory.process.size: 2048m

  taskmanager:
    image: thebozzcl/flink:arm64v8-1.11-scala_2.12-8-jre
    deploy:
      replicas: 4
      placement:
        constraints:
          - "node.labels.role==worker"
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 4
        taskmanager.memory.process.size: 2048m
