---
- hosts: managers[0]
  vars:
    stack_name: flink
    compose_url: 'https://raw.githubusercontent.com/thebozzcl/ClusterAutomationScripts/master/compose/docker_stack_flink/docker-compose.yml'
    compose_dest: '/tmp/flink_docker-compose.yml'
  tasks:
  - name: Install dependencies
    pip:
      name:
      - jsondiff
      - pyyaml
  - name: Copy compose file
    get_url:
      url: '{{ compose_url }}'
      dest: '{{ compose_dest }}'
  - name: Remove previous stack
    docker_stack:
      name: '{{ stack_name }}'
      state: absent
  - name: Start new stack
    docker_stack:
      name: '{{ stack_name }}'
      state: present
      compose:
      - '{{ compose_dest }}'
