---
- hosts: all
  become: yes
  tasks:
  - name: Install pip
    apt:
      pkg: python-pip
  - name: Install docker Python library
    apt:
      pkg: python-docker
- hosts: managers[0]
  vars:
    swarm_port: 2377
    host_ip: '{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}'
  tasks:
  - name: Initialize Docker swarm
    docker_swarm:
      state: present
      advertise_addr: '{{ host_ip }}:{{ swarm_port }}'
    register: swarm_info
  - name: Get join-tokens
    set_fact:
      worker_token: '{{ swarm_info.swarm_facts.JoinTokens.Worker }}'
      manager_token: '{{ swarm_info.swarm_facts.JoinTokens.Manager }}'
  - name: Add labels
    docker_node:
      hostname: '{{ inventory_hostname }}'
      labels:
        gpu: 'no'
        role: 'manager'
      labels_state: replace
- hosts: all
  vars:
    swarm_port: 2377
    worker_token: '{{ hostvars[groups["managers"][0]].worker_token }}'
    host_ip: '{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}'
  tasks:
  - name: Join Docker swarm
    docker_swarm:
      state: join
      remote_addrs: [ '{{ groups["managers"][0] }}:{{ swarm_port }}' ]
      join_token: '{{ worker_token }}'
      advertise_addr: '{{ host_ip }}:{{ swarm_port }}'
- hosts: managers[0]
  tasks:
  - name: Add labels to workers
    docker_node:
      hostname: '{{ item }}'
      labels:
        gpu: 'yes'
        role: 'worker'
      labels_state: replace
    loop: '{{ groups["workers"] }}'
