---
- hosts: all
  become: yes
  tasks:
  - name: create mount point
    file:
      path: /mnt/cluster_share
      state: directory
      mode: '0755'
  - name: install CIFS
    apt:
      pkg:
        - samba
        - samba-common-bin
        - smbclient
        - cifs-utils
      state: present
- hosts: workers
  become: yes
  tasks:
  - name: mount share in workers
    mount:
      path: /mnt/cluster_share
      src: //192.168.1.2/cluster_share
      fstype: cifs
      state: mounted
      opts: 'user=,password='
- hosts: managers
  become: yes
  tasks:
  - name: mount share in managers
    mount:
      path: /mnt/cluster_share
      src: //192.168.1.2/cluster_share
      fstype: cifs
      state: mounted
      opts: 'user=,password=,vers=2.0'
