- hosts: all
  become: yes
  tasks:
  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- hosts: workers
  become: yes
  tasks:
  - name: Add Docker GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - name: Add Docker APT repository
    shell: add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
- hosts: managers
  become: yes
  tasks:
  - name: Install Docker
    shell: curl -fsSL https://get.docker.com | sh
- hosts: all
  become: yes
  tasks:
  - name: Install Docker Engine
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: Add Ansible user to Docker group
    user:
      name: ansible
      groups: docker
      append: yes
